# Generated by Django 4.2.5 on 2023-10-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_username_user_email_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmation_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
