# Generated by Django 4.2.5 on 2023-10-03 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Контактный email')),
                ('commentary', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='начало рассылки')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='конец рассылки')),
                ('title', models.CharField(max_length=150, verbose_name='название рассылки')),
                ('period', models.CharField(choices=[('один раз', 'one_time'), ('ежедневно', 'daily'), ('еженедельно', 'weekly'), ('ежемесячно', 'monthly')], default='one', max_length=15, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('создана', 'created'), ('запущена', 'active'), ('завершена', 'completed')], default='new', max_length=15, verbose_name='состояние')),
                ('clients', models.ManyToManyField(to='main.client', verbose_name='клиенты')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщения для рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_time', models.DateTimeField(verbose_name='Дата и время попытки')),
                ('attempt_status', models.CharField(max_length=20, verbose_name='Статус попытки')),
                ('server_response', models.TextField(blank=True, verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailing')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылки',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.message', verbose_name='текст рассылки'),
        ),
    ]
